# Stage 1: build React Vite app
FROM node:22.17.0-alpine3.21 AS build
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source & env
COPY . .
COPY .env .

# Build Vite project
RUN npm run build

# Stage 2: serve static files with Nginx
FROM nginx:1.29.1-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
